DROP TABLE IF EXISTS `LoginSessions`;

DROP TABLE IF EXISTS `CourseSessions`;

DROP TABLE IF EXISTS `GameSessions`;

DROP TABLE IF EXISTS `Unbans`;

DROP TABLE IF EXISTS `Bans`;

DROP TABLE IF EXISTS `WipedRecords`;

DROP TABLE IF EXISTS `CheatedRecords`;

DROP TABLE IF EXISTS `SuspiciousRecords`;

DROP TABLE IF EXISTS `Records`;

DROP TABLE IF EXISTS `CheatedJumpstats`;

DROP TABLE IF EXISTS `SuspiciousJumpstats`;

DROP TABLE IF EXISTS `Jumpstats`;

DROP TABLE IF EXISTS `Servers`;

DROP TABLE IF EXISTS `CourseFilters`;

DROP TABLE IF EXISTS `CourseMappers`;

DROP TABLE IF EXISTS `Courses`;

DROP TABLE IF EXISTS `Mappers`;

DROP TABLE IF EXISTS `Maps`;

DROP TABLE IF EXISTS `Players`;

DROP TABLE IF EXISTS `Credentials`;

DROP TABLE IF EXISTS `PluginVersions`;
