CREATE TABLE IF NOT EXISTS AuditLogs (
  `id` INT8 NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(255) NOT NULL,
  `message` VARCHAR(255) NOT NULL,
  `fields` JSON,
  `created_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);
