CREATE TABLE IF NOT EXISTS Services (
  `id` INT8 UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `key` INT4 UNSIGNED NOT NULL,
  `role_flags` INT4 UNSIGNED NOT NULL DEFAULT 0,
  `created_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE (`name`)
);
