DROP FUNCTION IF EXISTS KZ_POINTS;

DROP TABLE IF EXISTS Unbans;

DROP TABLE IF EXISTS Bans;

DROP TABLE IF EXISTS PointDistributionData;

DROP TABLE IF EXISTS BestProRecords;

DROP TABLE IF EXISTS BestNubRecords;

DROP TABLE IF EXISTS RecordReplays;

DROP TABLE IF EXISTS Records;

DROP TABLE IF EXISTS JumpReplays;

DROP TABLE IF EXISTS Jumps;

DROP TABLE IF EXISTS CourseMappers;

DROP TABLE IF EXISTS Mappers;

DROP TABLE IF EXISTS CourseFilters;

DROP TABLE IF EXISTS Courses;

DROP TABLE IF EXISTS Maps;

DROP TABLE IF EXISTS Players;

DROP TABLE IF EXISTS Servers;

DROP TABLE IF EXISTS UserSessions;

DROP TABLE IF EXISTS Users;

DROP TABLE IF EXISTS AccessKeys;

DROP TABLE IF EXISTS PluginReleases;
